server.port=8085
spring.thymeleaf.cache=false
spring.datasource.generate-unique-name=false

taco.orders.pageSize=10

spring.data.mongodb.uri=mongodb+srv://altasuser:${MONGODB_PASSWORD}@cluster0.wueznfj.mongodb.net/tacoclouddb?retryWrites=true&w=majority